# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiBom < Formula
  desc "A tool to generate AIBOMs from HuggingFace models."
  homepage "https://github.com/manifest-cyber/ai-bom"
  version "0.0.1-beta.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manifest-cyber/ai-bom/releases/download/v0.0.1-beta.0/ai-bom_darwin_arm64.tar.gz"
      sha256 "cf496bf9790c7fe5bfa7591ee370ce274ca6a7973bc1c3f2e5af2b0df9c4a09f"

      def install
        bin.install "ai-bom"
        bash_completion.install "completions/ai-bom.bash" => "ai-bom"
        zsh_completion.install "completions/ai-bom.zsh" => "_ai-bom"
        fish_completion.install "completions/ai-bom.fish"
        man1.install "manpages/ai-bom.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/ai-bom/releases/download/v0.0.1-beta.0/ai-bom_darwin_amd64.tar.gz"
      sha256 "a1c39268e57d7dfdd5388276454e0224e396e723b642c9311a0c6f50259cc843"

      def install
        bin.install "ai-bom"
        bash_completion.install "completions/ai-bom.bash" => "ai-bom"
        zsh_completion.install "completions/ai-bom.zsh" => "_ai-bom"
        fish_completion.install "completions/ai-bom.fish"
        man1.install "manpages/ai-bom.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/ai-bom/releases/download/v0.0.1-beta.0/ai-bom_linux_armv7.tar.gz"
      sha256 "25334a1ffbc90f70d4bfb32e105d6fe4b612299fe131694784b1829a83411ce6"

      def install
        bin.install "ai-bom"
        bash_completion.install "completions/ai-bom.bash" => "ai-bom"
        zsh_completion.install "completions/ai-bom.zsh" => "_ai-bom"
        fish_completion.install "completions/ai-bom.fish"
        man1.install "manpages/ai-bom.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/ai-bom/releases/download/v0.0.1-beta.0/ai-bom_linux_amd64.tar.gz"
      sha256 "4865be4066beaa10703e48a7883ab4b97dc06b2d52e57855db03ff7deafd2ee5"

      def install
        bin.install "ai-bom"
        bash_completion.install "completions/ai-bom.bash" => "ai-bom"
        zsh_completion.install "completions/ai-bom.zsh" => "_ai-bom"
        fish_completion.install "completions/ai-bom.fish"
        man1.install "manpages/ai-bom.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/ai-bom/releases/download/v0.0.1-beta.0/ai-bom_linux_arm64.tar.gz"
      sha256 "d723b9b795c06bfb7958782e27a601c3fcb81046a65a123a50e77400448c1870"

      def install
        bin.install "ai-bom"
        bash_completion.install "completions/ai-bom.bash" => "ai-bom"
        zsh_completion.install "completions/ai-bom.zsh" => "_ai-bom"
        fish_completion.install "completions/ai-bom.fish"
        man1.install "manpages/ai-bom.1.gz"
      end
    end
  end
end
