# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AibomGen < Formula
  desc "A tool to generate AIBOMs from AI models."
  homepage "https://github.com/manifest-cyber/aibom-gen"
  version "0.1.0-alpha.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.12/aibom-gen_darwin_x86_64.tar.gz"
      sha256 "2cd49545f5f910ae5a3ca8dc156381b9a2d32f25dd35820ec328ce2c4b329301"

      define_method(:install) do
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.12/aibom-gen_darwin_arm64.tar.gz"
      sha256 "31597742fd0dc5c0716380efd5b33bdbe9cbc4a1b261213ec794ef50bab20735"

      define_method(:install) do
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.12/aibom-gen_linux_x86_64.tar.gz"
      sha256 "88096c8857fcf3540abe5073424fed13621379c8f7b281568517445adcf2ed59"
      define_method(:install) do
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.12/aibom-gen_linux_armv7.tar.gz"
      sha256 "f305152e7b57ac93e084d39ca15d800c495d1f4cd16a59dbf11d2765771b2df6"
      define_method(:install) do
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.12/aibom-gen_linux_arm64.tar.gz"
      sha256 "e830a6c4f81f6399348b83a9ab8c9d3242fe8d7658928fecf7dbe3f381ec6443"
      define_method(:install) do
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
  end
end
