# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AibomGen < Formula
  desc "A tool to generate AIBOMs from AI models."
  homepage "https://github.com/manifest-cyber/aibom-gen"
  version "0.1.0-alpha.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.3/aibom-gen_darwin_x86_64.tar.gz"
      sha256 "847ca1892980f31a35dd643470111f39cf97fc17eae9d8665514345f693070b1"

      def install
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.3/aibom-gen_darwin_arm64.tar.gz"
      sha256 "495a49d5612c30ded893ae0d346dcade0af313b7dae39bf531999cacc1f7e0d1"

      def install
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.3/aibom-gen_linux_x86_64.tar.gz"
      sha256 "33e459e9a0756eb6c57f9aab03f12c46ac49b6495e75193e2325dafb43438083"
      def install
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.3/aibom-gen_linux_armv7.tar.gz"
      sha256 "adad97d987d1b82dfaa1d8bf83dd5aa6977a9b672789b8fdfa4f32ba3b3a0c8f"
      def install
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/aibom-gen/releases/download/v0.1.0-alpha.3/aibom-gen_linux_arm64.tar.gz"
      sha256 "efec36b20b258dd8cd06f05f22b9c28334addd495c9eac5ae405a258b1f5d64d"
      def install
        bin.install "aibom-gen"
        bash_completion.install "completions/aibom-gen.bash" => "aibom-gen"
        zsh_completion.install "completions/aibom-gen.zsh" => "_aibom-gen"
        fish_completion.install "completions/aibom-gen.fish"
        man1.install "manpages/aibom-gen.1.gz"
      end
    end
  end
end
