# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manifest < Formula
  desc "a toolkit for sbom generation, merge and publish to the Manifest platform"
  homepage "https://github.com/manifest-cyber/cli"
  version "0.12.1-beta.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/cli/releases/download/v0.12.1-beta.0/manifest_darwin_x86_64.tar.gz"
      sha256 "c19a65361bcd8c1e21ef7ba3aa4245a02f70a048c6c2f7d2df01c6d38c4917ab"

      def install
        bin.install "manifest"
        bash_completion.install "completions/manifest.bash" => "manifest"
        zsh_completion.install "completions/manifest.zsh" => "_manifest"
        fish_completion.install "completions/manifest.fish"
        man1.install "manpages/manifest.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manifest-cyber/cli/releases/download/v0.12.1-beta.0/manifest_darwin_arm64.tar.gz"
      sha256 "3f620a24a94cdf5e29e4f7b645c86531d6f4d9d01c6d161e37671d53c7e0cb11"

      def install
        bin.install "manifest"
        bash_completion.install "completions/manifest.bash" => "manifest"
        zsh_completion.install "completions/manifest.zsh" => "_manifest"
        fish_completion.install "completions/manifest.fish"
        man1.install "manpages/manifest.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/cli/releases/download/v0.12.1-beta.0/manifest_linux_arm64.tar.gz"
      sha256 "52522f2216e65d4149f4535217aeaa4993e84dbffaba4548777cae40feebfcdb"

      def install
        bin.install "manifest"
        bash_completion.install "completions/manifest.bash" => "manifest"
        zsh_completion.install "completions/manifest.zsh" => "_manifest"
        fish_completion.install "completions/manifest.fish"
        man1.install "manpages/manifest.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/cli/releases/download/v0.12.1-beta.0/manifest_linux_x86_64.tar.gz"
      sha256 "fd46fe9042f5683209e5c072200208476e5cdb44e88406caa143b058636ff809"

      def install
        bin.install "manifest"
        bash_completion.install "completions/manifest.bash" => "manifest"
        zsh_completion.install "completions/manifest.zsh" => "_manifest"
        fish_completion.install "completions/manifest.fish"
        man1.install "manpages/manifest.1.gz"
      end
    end
  end
end
