# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MlbomGenerator < Formula
  desc "A tool to generate MLBOMs from HuggingFace models."
  homepage "https://github.com/manifest-cyber/mlbom-generator"
  version "0.0.1-beta.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manifest-cyber/mlbom-generator/releases/download/v0.0.1-beta.0/mlbom-generator_darwin_arm64.tar.gz"
      sha256 "20cf639c53b54be6acc474b83dbf56d38ccbc91aea4cfc8c732fe84280f3cee5"

      def install
        bin.install "mlbom-generator"
        bash_completion.install "completions/mlbom-generator.bash" => "mlbom-generator"
        zsh_completion.install "completions/mlbom-generator.zsh" => "_mlbom-generator"
        fish_completion.install "completions/mlbom-generator.fish"
        man1.install "manpages/mlbom-generator.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/mlbom-generator/releases/download/v0.0.1-beta.0/mlbom-generator_darwin_amd64.tar.gz"
      sha256 "d40944dc530e830aca95f498c7d995a538ad100051695949962bcbdb69e0ca09"

      def install
        bin.install "mlbom-generator"
        bash_completion.install "completions/mlbom-generator.bash" => "mlbom-generator"
        zsh_completion.install "completions/mlbom-generator.zsh" => "_mlbom-generator"
        fish_completion.install "completions/mlbom-generator.fish"
        man1.install "manpages/mlbom-generator.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/mlbom-generator/releases/download/v0.0.1-beta.0/mlbom-generator_linux_armv7.tar.gz"
      sha256 "4306c6b6f8d820648032f4b4c3bc305b7ec7a8f81a25318bd4e3ef658cae7b47"

      def install
        bin.install "mlbom-generator"
        bash_completion.install "completions/mlbom-generator.bash" => "mlbom-generator"
        zsh_completion.install "completions/mlbom-generator.zsh" => "_mlbom-generator"
        fish_completion.install "completions/mlbom-generator.fish"
        man1.install "manpages/mlbom-generator.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/mlbom-generator/releases/download/v0.0.1-beta.0/mlbom-generator_linux_arm64.tar.gz"
      sha256 "c3de58598f0f167c5948115b64cbc70a4370e37db206b1ce4831f2c358958892"

      def install
        bin.install "mlbom-generator"
        bash_completion.install "completions/mlbom-generator.bash" => "mlbom-generator"
        zsh_completion.install "completions/mlbom-generator.zsh" => "_mlbom-generator"
        fish_completion.install "completions/mlbom-generator.fish"
        man1.install "manpages/mlbom-generator.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/mlbom-generator/releases/download/v0.0.1-beta.0/mlbom-generator_linux_amd64.tar.gz"
      sha256 "fb4f111ea0ee89f7fa42a3203b18bf945be0d9deb787d927c1656269104afc98"

      def install
        bin.install "mlbom-generator"
        bash_completion.install "completions/mlbom-generator.bash" => "mlbom-generator"
        zsh_completion.install "completions/mlbom-generator.zsh" => "_mlbom-generator"
        fish_completion.install "completions/mlbom-generator.fish"
        man1.install "manpages/mlbom-generator.1.gz"
      end
    end
  end
end
